In [2]:
import pandas as pd
import numpy as np

In [6]:
people = {
    "first": ["Corey", "Jane", "John", "Chris", np.nan, None, 'NA'],
    "last": ["Schafer", "Doe", "Doe", "Schafer", np.nan, np.nan, "Missing"],
    "email": ["CoreyMSchafer@gmail.com", "JaneDoe@gmail.com", "JohnDoe@gmail.com", None, np.nan, "Anonymous@gmail.com", 'NA'],
    "age":['33','53', '63', '36', None, None, 'Missing']
}

In [7]:
df = pd.DataFrame(people)

In [8]:
df

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@gmail.com       53
2   John      Doe        JohnDoe@gmail.com       63
3  Chris  Schafer                      NaN       36
4    NaN      NaN                      NaN      NaN
5    NaN      NaN      Anonymous@gmail.com      NaN
6     NA  Missing                       NA  Missing

In [41]:
df['last']

0    Schafer
1        Doe
2        Doe
Name: last, dtype: str

In [42]:
df['last'] == "Doe"

0    False
1     True
2     True
Name: last, dtype: bool

In [43]:
filt = df['last'] == "Doe"
df[filt]

  first last              email
1  Jane  Doe  JaneDoe@gmail.com
2  John  Doe  JohnDoe@gmail.com

In a similar fashion, we can also execute this using loc

In [44]:
df.loc[filt]

  first last              email
1  Jane  Doe  JaneDoe@gmail.com
2  John  Doe  JohnDoe@gmail.com

In [45]:
filte = (df['first'] == "John") & (df['last'] == "Doe")

In [46]:
df[filte]

  first last              email
2  John  Doe  JohnDoe@gmail.com

29th May, 2026

In [47]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [48]:
df.columns = [x.upper() for x in df.columns]

In [49]:
df.loc[2, ['last', 'email']] = ['Tait', 'johntait@gmail.com']

In [50]:
df

   FIRST     LAST                    EMAIL  last               email
0  Corey  Schafer  CoreyMSchafer@gmail.com   NaN                 NaN
1   Jane      Doe        JaneDoe@gmail.com   NaN                 NaN
2   John      Doe        JohnDoe@gmail.com  Tait  johntait@gmail.com

In [51]:
df

   FIRST     LAST                    EMAIL  last               email
0  Corey  Schafer  CoreyMSchafer@gmail.com   NaN                 NaN
1   Jane      Doe        JaneDoe@gmail.com   NaN                 NaN
2   John      Doe        JohnDoe@gmail.com  Tait  johntait@gmail.com

How to perform operation on all the rows of a particular column

In [52]:
df['email'].str.lower()

0                   NaN
1                   NaN
2    johntait@gmail.com
Name: email, dtype: str

In [53]:
df

   FIRST     LAST                    EMAIL  last               email
0  Corey  Schafer  CoreyMSchafer@gmail.com   NaN                 NaN
1   Jane      Doe        JaneDoe@gmail.com   NaN                 NaN
2   John      Doe        JohnDoe@gmail.com  Tait  johntait@gmail.com

In [54]:
df['email'] = df['email'].str.lower()

In [55]:
df

   FIRST     LAST                    EMAIL  last               email
0  Corey  Schafer  CoreyMSchafer@gmail.com   NaN                 NaN
1   Jane      Doe        JaneDoe@gmail.com   NaN                 NaN
2   John      Doe        JohnDoe@gmail.com  Tait  johntait@gmail.com

In [ ]:
df

In [ ]:
df['email'] = df['email'].apply(lambda x: x.lower())

In [ ]:
df

In [ ]:
df.map(len)

In [ ]:
df['first'].map({'Corey': 'Jorey', 'Jane': 'Wane'})

In [ ]:
df['first'].replace({'Corey': 'Jorey', 'Jane': 'Wane'})

In [ ]:
df

In [ ]:
df.drop('last', axis=1)

In [ ]:
df

In [ ]:
df = df.drop('last', axis=1)

In [ ]:
df

In [ ]:
df = df.drop('email', axis=1)

In [ ]:
df

In [ ]:
df.columns

In [ ]:
df.columns = df.columns.str.lower()

In [ ]:
df

In [ ]:
df['full_name'] = df['first'] + ' ' + df['last']

In [ ]:
df

In [ ]:
df[['first1c', 'first2c']] = df['full_name'].str.split(' ', expand=True)

In [ ]:
df

In [ ]:
df = df.drop(columns = ['first1c', 'first2c'])

In [ ]:
df

In [ ]:
df = df.drop('full_name', axis=1)

In [ ]:
df

In [ ]:
people = {
    "first": ["Corey", "Jane"],
    "last": ["Stark", "Rogers"],
    "email": ["ironman@avenge.com", "cap@avenge.com"]
}
df2 = pd.DataFrame(people)

In [ ]:
df2

In [ ]:
df.append(df2, ignore_index = True)

In [ ]:
df = pd.concat([df,df2], ignore_index=True)

In [ ]:
df

In [ ]:
df = df.drop(index=4)

In [ ]:
df

In [ ]:
df.sort_values(by='last')

In [ ]:
df.sort_values(by='last', ascending=False)

In [ ]:
df.sort_index()

In [ ]:
df.sort_values(by='LAST')

In [ ]:
df

In [59]:
df.loc[len(df)] = ['Adam', 'Doe', 'adamdoe@gmail.com', 'NA', 'NA']

In [60]:
df

   FIRST     LAST                    EMAIL  last               email
0  Corey  Schafer  CoreyMSchafer@gmail.com   NaN                 NaN
1   Jane      Doe        JaneDoe@gmail.com   NaN                 NaN
2   John      Doe        JohnDoe@gmail.com  Tait  johntait@gmail.com
3   Adam      Doe        adamdoe@gmail.com    NA                  NA

In [61]:
df = df.replace('NA', np.nan)

In [62]:
df

   FIRST     LAST                    EMAIL  last               email
0  Corey  Schafer  CoreyMSchafer@gmail.com   NaN                 NaN
1   Jane      Doe        JaneDoe@gmail.com   NaN                 NaN
2   John      Doe        JohnDoe@gmail.com  Tait  johntait@gmail.com
3   Adam      Doe        adamdoe@gmail.com   NaN                 NaN

In [64]:
df = df.drop(columns=['last', 'email'])

In [65]:
df

   FIRST     LAST                    EMAIL
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com
3   Adam      Doe        adamdoe@gmail.com

In [72]:
df.columns.str.lower()

Index(['first', 'last', 'email'], dtype='str')

In [73]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com

In [74]:
df.sort_values(by=['last','first'], ascending = [False, True])

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com

June 04, 2026

In [9]:
df

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@gmail.com       53
2   John      Doe        JohnDoe@gmail.com       63
3  Chris  Schafer                      NaN       36
4    NaN      NaN                      NaN      NaN
5    NaN      NaN      Anonymous@gmail.com      NaN
6     NA  Missing                       NA  Missing

In [10]:
df.dropna()

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@gmail.com       53
2   John      Doe        JohnDoe@gmail.com       63
6     NA  Missing                       NA  Missing

In [11]:
df.dropna(axis='index', how = 'all')

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@gmail.com       53
2   John      Doe        JohnDoe@gmail.com       63
3  Chris  Schafer                      NaN       36
5    NaN      NaN      Anonymous@gmail.com      NaN
6     NA  Missing                       NA  Missing

In [12]:
df.dropna(axis='index', subset=['email'])

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@gmail.com       53
2   John      Doe        JohnDoe@gmail.com       63
5    NaN      NaN      Anonymous@gmail.com      NaN
6     NA  Missing                       NA  Missing

In [13]:
df.replace('NA', np.nan, inplace=True)

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@gmail.com       53
2   John      Doe        JohnDoe@gmail.com       63
3  Chris  Schafer                      NaN       36
4    NaN      NaN                      NaN      NaN
5    NaN      NaN      Anonymous@gmail.com      NaN
6    NaN  Missing                      NaN  Missing

In [14]:
df.replace('Missing', np.nan, inplace=True)

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@gmail.com   53
2   John      Doe        JohnDoe@gmail.com   63
3  Chris  Schafer                      NaN   36
4    NaN      NaN                      NaN  NaN
5    NaN      NaN      Anonymous@gmail.com  NaN
6    NaN      NaN                      NaN  NaN

In [15]:
df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6   True   True   True   True

In [16]:
df.fillna(0)

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@gmail.com  53
2   John      Doe        JohnDoe@gmail.com  63
3  Chris  Schafer                        0  36
4      0        0                        0   0
5      0        0      Anonymous@gmail.com   0
6      0        0                        0   0

In [17]:
df.dtypes

first    str
last     str
email    str
age      str
dtype: object