In [1]:
import pandas as pd
import numpy as np

In [35]:
df = pd.read_csv("C:\\Users\\vijit\\Downloads\\time_series_practice_data.csv")

In [36]:
df

,Date,Sales_USD,Foot_Traffic,Temperature_C,Promo_Type,Customer_Satisfaction
0,2023-01-01,87.15,167,-1.6,NaN,4.65
1,2023-01-02,117.77,236,-0.4,NaN,3.56
2,2023-01-03,133.00,266,-0.4,Discount,4.75
3,2023-01-04,140.57,335,5.4,BOGO,4.90
4,2023-01-05,115.44,267,7.7,BOGO,3.92
...,...,...,...,...,...,...
1091,2025-12-27,153.12,338,4.1,NaN,4.75
1092,2025-12-28,153.16,351,1.1,NaN,4.37
1093,2025-12-29,213.09,454,2.8,NaN,3.68
1094,2025-12-30,231.58,525,3.2,NaN,3.93
1095,2025-12-31,216.63,392,2.9,NaN,3.78

In [5]:
df.loc[0, 'Date'].day_name()

AttributeError: 'str' object has no attribute 'day_name'

In [11]:
df['Date'] = pd.to_datetime(df['Date'], format = '%Y-%m-%d %I-%p')

In [13]:
df['Date']

0      2023-01-01
1      2023-01-02
2      2023-01-03
3      2023-01-04
4      2023-01-05
          ...
1091   2025-12-27
1092   2025-12-28
1093   2025-12-29
1094   2025-12-30
1095   2025-12-31
Name: Date, Length: 1096, dtype: datetime64[us]

In [8]:
df.loc[0, 'Date'].day_name()

'Sunday'

In [10]:
df.loc[0, 'Date'].month_name()

'January'

In [16]:
df['Date'].dt.day_name()

0          Sunday
1          Monday
2         Tuesday
3       Wednesday
4        Thursday
          ...
1091     Saturday
1092       Sunday
1093       Monday
1094      Tuesday
1095    Wednesday
Name: Date, Length: 1096, dtype: str

In [17]:
df['DayofWeek'] = df['Date'].dt.day_name()

In [18]:
df

,Date,Sales_USD,Foot_Traffic,Temperature_C,Promo_Type,Customer_Satisfaction,DayofWeek
0,2023-01-01,87.15,167,-1.6,NaN,4.65,Sunday
1,2023-01-02,117.77,236,-0.4,NaN,3.56,Monday
2,2023-01-03,133.00,266,-0.4,Discount,4.75,Tuesday
3,2023-01-04,140.57,335,5.4,BOGO,4.90,Wednesday
4,2023-01-05,115.44,267,7.7,BOGO,3.92,Thursday
...,...,...,...,...,...,...,...
1091,2025-12-27,153.12,338,4.1,NaN,4.75,Saturday
1092,2025-12-28,153.16,351,1.1,NaN,4.37,Sunday
1093,2025-12-29,213.09,454,2.8,NaN,3.68,Monday
1094,2025-12-30,231.58,525,3.2,NaN,3.93,Tuesday
1095,2025-12-31,216.63,392,2.9,NaN,3.78,Wednesday

In [19]:
df['Date'].min()

Timestamp('2023-01-01 00:00:00')

In [20]:
df['Date'].max()

Timestamp('2025-12-31 00:00:00')

In [21]:
df['Date'].max() - df['Date'].min()

Timedelta('1095 days 00:00:00')

In [23]:
filt = (df['Date'] >= '2024')
df.loc[filt]

,Date,Sales_USD,Foot_Traffic,Temperature_C,Promo_Type,Customer_Satisfaction,DayofWeek
365,2024-01-01,146.02,328,-0.9,Discount,4.84,Monday
366,2024-01-02,160.82,366,6.4,BOGO,4.34,Tuesday
367,2024-01-03,154.58,326,3.1,Discount,4.53,Wednesday
368,2024-01-04,150.48,283,2.7,NaN,3.95,Thursday
369,2024-01-05,157.05,345,4.7,NaN,4.06,Friday
...,...,...,...,...,...,...,...
1091,2025-12-27,153.12,338,4.1,NaN,4.75,Saturday
1092,2025-12-28,153.16,351,1.1,NaN,4.37,Sunday
1093,2025-12-29,213.09,454,2.8,NaN,3.68,Monday
1094,2025-12-30,231.58,525,3.2,NaN,3.93,Tuesday
1095,2025-12-31,216.63,392,2.9,NaN,3.78,Wednesday

In [37]:
df.set_index('Date')

,Sales_USD,Foot_Traffic,Temperature_C,Promo_Type,Customer_Satisfaction
Date,,,,,
2023-01-01,87.15,167,-1.6,NaN,4.65
2023-01-02,117.77,236,-0.4,NaN,3.56
2023-01-03,133.00,266,-0.4,Discount,4.75
2023-01-04,140.57,335,5.4,BOGO,4.90
2023-01-05,115.44,267,7.7,BOGO,3.92
...,...,...,...,...,...
2025-12-27,153.12,338,4.1,NaN,4.75
2025-12-28,153.16,351,1.1,NaN,4.37
2025-12-29,213.09,454,2.8,NaN,3.68
2025-12-30,231.58,525,3.2,NaN,3.93
2025-12-31,216.63,392,2.9,NaN,3.78

In [39]:
df

,Date,Sales_USD,Foot_Traffic,Temperature_C,Promo_Type,Customer_Satisfaction
0,2023-01-01,87.15,167,-1.6,NaN,4.65
1,2023-01-02,117.77,236,-0.4,NaN,3.56
2,2023-01-03,133.00,266,-0.4,Discount,4.75
3,2023-01-04,140.57,335,5.4,BOGO,4.90
4,2023-01-05,115.44,267,7.7,BOGO,3.92
...,...,...,...,...,...,...
1091,2025-12-27,153.12,338,4.1,NaN,4.75
1092,2025-12-28,153.16,351,1.1,NaN,4.37
1093,2025-12-29,213.09,454,2.8,NaN,3.68
1094,2025-12-30,231.58,525,3.2,NaN,3.93
1095,2025-12-31,216.63,392,2.9,NaN,3.78

In [41]:
df.loc[0, 'Date']

'2023-01-01'

In [42]:
df.loc[0]

Date                     2023-01-01
Sales_USD                     87.15
Foot_Traffic                    167
Temperature_C                  -1.6
Promo_Type                      NaN
Customer_Satisfaction          4.65
Name: 0, dtype: object